# This is a basic workflow that is manually triggered

name: Commit workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Commit changes
    - uses: EndBug/add-and-commit@v5
      with:
        author_name: Your name
        author_email: mail@example.com
        message: "Your commit message"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

